name: DeathBarrel
version: '${project.version}'
main: io.github.sweetenpotato.deathbarrel.Main
api-version: 1.18
permissions:
  deathBarrel.loot:
    description: If you have this permission, it allows you to place the deathbarrel when you died.
    default: true
  deathBarrel.getMessage:
    description: If you have this permission, it allows you to get message about location of your death-barrel location.
    default: true
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10